# Generated by Django 3.0 on 2022-04-05 15:10

from django.db import migrations, models
import django_simple_coupons.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=django_simple_coupons.helpers.get_random_code, max_length=7, unique=True, verbose_name='Coupon Code'),
        ),
    ]
