# Generated by Django 4.0.2 on 2022-04-21 11:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='publish_date',
            field=models.DateTimeField(default=datetime.date(2022, 4, 21)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
