# Generated by Django 4.0.2 on 2022-05-11 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='publish_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 11)),
        ),
    ]
