# Generated by Django 3.0 on 2022-05-06 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupgen', '0002_coupon_expire_date_coupon_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='publish_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 6)),
        ),
        migrations.AlterField(
            model_name='coupon_gener',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
